# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\source\mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QEtest(object):
    def setupUi(self, QEtest):
        QEtest.setObjectName("QEtest")
        QEtest.resize(428, 358)
        self.centralwidget = QtWidgets.QWidget(QEtest)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(200, 70, 201, 91))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 290, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 290, 91, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 181, 261))
        self.label.setObjectName("label")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(200, 240, 201, 41))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 220, 201, 18))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(200, 30, 201, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(200, 170, 201, 51))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        QEtest.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QEtest)
        self.statusbar.setObjectName("statusbar")
        QEtest.setStatusBar(self.statusbar)

        self.retranslateUi(QEtest)
        QtCore.QMetaObject.connectSlotsByName(QEtest)

    def retranslateUi(self, QEtest):
        _translate = QtCore.QCoreApplication.translate
        QEtest.setWindowTitle(_translate("QEtest", "QEtest"))
        self.pushButton.setText(_translate("QEtest", "Choose input file"))
        self.plainTextEdit_2.setPlainText(_translate("QEtest", "replaced here by Kpoint/ecut"))
        self.pushButton_2.setText(_translate("QEtest", "Ecut-test"))
        self.pushButton_3.setText(_translate("QEtest", "K-test"))
        self.label.setText(_translate("QEtest", "Please type input\n"
"parameter. e.g.\n"
"For ecut-test\n"
"#start\n"
"25..50..60\n"
"#end\n"
"For Kpoint-test\n"
"#start\n"
"1,2,1  \\\\  \n"
"1,2,2 \\\\  \n"
"2,3,2 \\\\  \n"
"#end\n"
"Don\'t type lines with\n"
"\"#\""))
        self.plainTextEdit_3.setPlainText(_translate("QEtest", "mpirun -n 12 pw.x"))
        self.label_2.setText(_translate("QEtest", "Type command here. e.g."))
        self.plainTextEdit.setPlainText(_translate("QEtest", "normally scf.in"))
        self.plainTextEdit_4.setPlainText(_translate("QEtest", "replaced here by ecut/Kpoint"))
